import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import { checkout } from "../checkout"

export default function Home() {
  return (
    <div className={styles.container} id="hello">
    <div className="card">
      <Head>
        <title>Donate to a cause</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>For the world</h1>
        <div className={styles.grid}>
          <div>
            <Image
              src="/images/donate.jpg"
              alt="NFT"
              width={400}
              height={400}
            />
            <p style={{justifyContent:'center',alignItems:'center',textAlign:'center', marginRight:'40px'}}>A little help is nothing</p>
            <button style={{padding:'12px', marginLeft:'130px',border:'none'}} onClick={(() => {
              checkout({
                lineItems: [
                  {
                    price: "price_1OW87HSD1t9aK7D6B961jZFn",
                    quantity: 1
                  }
                ]
              })
            })}>Donate!</button>
          </div>
        </div>
      </main>
      </div>
    </div>
  )
}
